// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Tema1;

/************************************************************/
/**
 * 
 */
public class Activitati {
	/**
	 * 
	 */
	private String numeActivitate;
	/**
	 * 
	 */
	private String descriere;
	/**
	 * 
	 */
	private int numarMaximVoluntari;

	/**
	 * 
	 * @return 
	 */
	public boolean redenumireActivitate() {
		return true;
	}
};
