// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Tema1;

/************************************************************/
/**
 * 
 */
public class Echipa {
	/**
	 * 
	 */
	private Voluntar liderEchipa;
	/**
	 * 
	 */
	public Voluntar[] voluntar;
	/**
	 * 
	 */
	public Raport raport;
	/**
	 * 
	 */
	private Activitati activitateEchipa;
	/**
	 * 
	 */
	private String numeEchipa;

	/**
	 * 
	 * @param nrVoluntar 
	 */
	public void asignareLider(int nrVoluntar) {
	}

	/**
	 * 
	 * @param nrVoluntar 
	 * @param rol 
	 */
	public void asignareRol(int nrVoluntar, String rol) {
	}

	/**
	 * 
	 * @param ocupatie 
	 */
	public void completareRaport(String ocupatie) {
	}

	/**
	 * 
	 */
	public void eliberareRaport() {
	}
};
