// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Tema1;

/************************************************************/
/**
 * 
 */
public class Eveniment {
	/**
	 * 
	 */
	private String locatie;
	/**
	 * 
	 */
	private String numeEveniment;
	/**
	 * 
	 */
	public Echipa[] echipa;
	/**
	 * 
	 */
	public Program program;
	/**
	 * 
	 */
	public Manager manager;

	/**
	 * 
	 */
	public void afisareVoluntari() {
	}

	/**
	 * 
	 * @param intervaleOrare 
	 */
	public void creareProgram(String intervaleOrare) {
	}
};
