// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Tema1;

/************************************************************/
/**
 * 
 */
public class Manager extends Persoana{

    private Eveniment[] evenimente;
    private static final int NR_MAX_EVENIMENTE = 10;
    private int nrEvenimente;

    public Manager(String username, String parola, String nume, String prenume, int varsta){
        super(username,parola,nume,prenume,varsta);
        nrEvenimente=0;
        evenimente = new Eveniment[NR_MAX_EVENIMENTE];
    }

    public Eveniment[] getEveniment() {
        return evenimente;
    }

    public boolean creareEveniment(Eveniment eveniment) {
        if (nrEvenimente < NR_MAX_EVENIMENTE) {
            for (int i = 0; i < nrEvenimente; i++)
                if (evenimente[i].equals(eveniment)) {
                    System.out.println("Eveniment existenta");
                    return false;
                }
            this.evenimente[nrEvenimente++] = eveniment;
            System.out.println("Eveniment adaugata");
            return true;
        }
        System.out.println("Numar maxim de evenimente atins");
        return false;
    }

};
