// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Tema1;

/************************************************************/
/**
 * 
 */
public class Persoana {
	/**
	 * 
	 */
	private String nume;
	/**
	 * 
	 */
	private String prenume;
	/**
	 * 
	 */
	private int varsta;
	/**
	 * 
	 */
	public User user;

	/**
	 * 
	 */
	public void afisare() {
	}
};
