// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Tema1;

/************************************************************/
/**
 * 
 */
public class Program {
	/**
	 * 
	 */
	public Activitati[] activitati;
	/**
	 * 
	 */
	private String[] intervalOrar;

	/**
	 * 
	 * @param activitate 
	 * @return 
	 */
	public boolean adaugareActivitate(Activitati activitate) {
	}

	/**
	 * 
	 * @return 
	 */
	public boolean stergereActivitate() {
	}
};
