// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Tema1;

/************************************************************/
/**
 * 
 */
public class Raport {
	/**
	 * 
	 */
	private String[] istoricOcupatii;

	/**
	 * 
	 */
	public void afisare() {
	}
};
