// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Tema1;

/************************************************************/
/**
 * 
 */
public class User {
	/**
	 * 
	 */
	private String username;
	/**
	 * 
	 */
	private String parola;

	/**
	 * 
	 */
	public void afisare() {
		System.out.println("Username: " + this.username);
		System.out.println("Parola: " + this.parola);
	}

	public User(String username, String parola) {
		super();
		this.username = username;
		this.parola = parola;
	}

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getParola() {
		return parola;
	}

	public void setParola(String parola) {
		this.parola = parola;
	}
	
	
};
