// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Tema1;

/************************************************************/
/**
 * 
 */
public class User {
	/**
	 * 
	 */
	private String username;
	/**
	 * 
	 */
	private String parola;

	/**
	 *
	 */
	public void afisare() {
	}
};
